ID: Matching 
SEED: 42
WEIGHTS: None 

TRAIN:
    LR: 0.0001
    BATCH_SIZE: 256
    NUM_WORKERS: 8
MODEL:
  VISUAL_MODEL:
    NAME: resnext101_32x8d 
    FINE_TUNING: False 
    HIDDEN_DIM: 256 
    DROPOUT: 0.3
  LANG_MODEL:
    NAME: vinai/phobert-base
    FINE_TUNING: False 
    HIDDEN_DIM: 256 
    DROPOUT: 0.3
  CROSS_FEATURE_DIM: 64

METRIC:
  RECALL: [1, 5, 10]
  
DATASET:
  TRAIN:
    IMG_SPLITS: [
      'mscoco_train_vi_vi',
      'mscoco_nominival_vi_vi',
      'vgnococo_vi_vi',
      ]
    LANG_SPLITS: ['mscoco']
  VAL:
    IMG_SPLITS: [ 'mscoco_minival_vi_vi', ]
    LANG_SPLITS: ['mscoco']